### PR TITLE
Translation for Brazilian Portuguese

### PR DESCRIPTION
**Pull request by git-jr**
I extracted the user-visible texts to the corresponding string.xml files, and translated them into Brazilian Portuguese.
This can also assist in translation into other languages.

### CODE REVIEW

**Review by yrom — CHANGES_REQUESTED** [review]
The file `releases/Screen Recorder 2.4.2 pt-br.apk` should not be added to git.

**Comment by git-jr** [comment]
I reversed the commit that added the Screen Recorder 2.4.2 pt-br.apk, that's enough?

**Review by git-jr — COMMENTED** [review]
I reversed the commit that added the Screen Recorder 2.4.2 pt-br.apk, that's enough?

**Comment by yrom** [comment]
merged, thx

**Pull request merged**
